stages:
  - test

check_version:
  stage: test
  image: alpine:latest
  services:
    - docker:19.03.12-dind # Docker-in-Docker 服務
  script:
    - echo "Checking Alpine version..."
    - cat /etc/os-release
    - uname -a
    - docker --version
