apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: backend-propagationpolicy-gateway
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: backend-deployment-gateway
    - apiVersion: v1
      kind: Service
      name: backend-service-gateway
    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      name: http-backend
  placement:
    clusterAffinity:
      clusterNames:
        - cn-gke-1
        - cn-gke-2
        - cn-gke-3
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - cn-gke-1
            weight: 2
          - targetCluster:
              clusterNames:
                - cn-gke-2
            weight: 3
          - targetCluster:
              clusterNames:
                - cn-gke-3
            weight: 2
