version: '3'

services:
  billing-service:
    image: backend-microsvcs-billing-system
    build:
      context: ../
      dockerfile: docker/billing/Dockerfile
  notification-service:
    image: backend-microsvcs-notification-system
    build:
      context: ../
      dockerfile: docker/notification/Dockerfile
  ordering-service:
    image: backend-microsvcs-ordering-system
    build:
      context: ../
      dockerfile: docker/ordering/Dockerfile
  rating-service:
    image: backend-microsvcs-rating-system
    build:
      context: ../
      dockerfile: docker/rating/Dockerfile
  user-mgmt-service:
    image: backend-microsvcs-user-mgmt-system
    build:
      context: ../
      dockerfile: docker/user-mgmt/Dockerfile
